package dev.ele;

public enum Usage {
    GOVERNMENT, FIBRE_OPTIC, HOSPITAL, FIRE_STATION, SCHOOL, CHURCH, ROAD, AIRPORT, TRAIN_STATION, BUS_STATION,
    SEA_PORT, SOLAR_FARM, WIND_FARM, NUCLEAR_PLANT, DAM, OBSERVATORY, POWER_LINE, POWER_PLANT, RAIL, WALK_PATH,
    POLICE_STATION
}